project:
  type: website

website:
  title: "R-Lunches"
  navbar:
    left:
      - href: about.qmd
        text: What? / Quoi?
      - href: start_with_r.qmd
        text: Learn / Apprendre
      - href: index.qmd
        text: Next / Prochain R-lunches
      - href: r_at_unige.qmd
        text: Unige
      - href: mailing_list.qmd
        text: Mailing list

format:
  html:
    theme:
      light: [lumen, light.scss]
      dark: [lumen, dark.scss]
    max-width: 2000px
    fontsize: 24px

editor: visual

