---
title: "R à l'Unige"
format: html
---

### Ressources en ligne

-   [EduTechWiki-Unige](http://edutechwiki.unige.ch/fr/Tutoriels_R) - une mine de tutoriels pour R
-   [Liste statinfo](https://listes.unige.ch/sympa/info/statinfo) - séminaires de statistiques organisés à l’Unige

### Où trouver R dans les cours de l’Unige

**Faculté d’Économie et de Management**
-   [Master de statistiques](http://www.unige.ch/gsem/rcs/master/program/)
**Faculté de Psychologie et des Sciences de l’Éducation**
-   Enseignements du [Groupe Méthodologie et Analyse de Données](http://www.unige.ch/fapse/mad/services/)
**Faculté des Sciences**
-   [Statistiques appliquées](http://wadme.unige.ch:3149/pls/opprg/w_det_cours.debut?p_code_cours=14B951&p_plan_is=0&p_langue=1&p_frame=N&p_mode=PGC&p_annee=2015&p_suffixe=&p_grtri=)
-   [Mathématiques générales - statistique](http://wadme.unige.ch:3149/pls/opprg/w_det_cours.debut?p_code_cours=11M002&p_plan_is=0&p_langue=1&p_frame=N&p_mode=PGC&p_annee=2015&p_suffixe=&p_grtri=)
-   [Biostatistiques I](http://wadme.unige.ch:3149/pls/opprg/w_det_cours.debut?p_code_cours=11M004&p_plan_is=0&p_langue=1&p_frame=N&p_mode=PGC&p_annee=2015&p_suffixe=&p_grtri=)
**Faculté des Sciences de la Société**
-   [Analyse de données d’enquêtes](http://wadme.unige.ch:3149/pls/opprg/w_det_cours.debut?p_code_cours=T415009&p_plan_is=0&p_langue=1&p_frame=N&p_mode=PGC&p_annee=2015&p_suffixe=&p_grtri=)
-   [Analyse de données longitudinales](http://wadme.unige.ch:3149/pls/opprg/w_det_cours.debut?p_code_cours=T415012&p_plan_is=0&p_langue=1&p_frame=N&p_mode=PGC&p_annee=2015&p_suffixe=&p_grtri=)
**Institut des Sciences de l’Environnement**
-   [Maîtrise universitaire en sciences de l’environnement](http://wadme.unige.ch:3149/pls/opprg/w_rech_cours.result_fac?p_langue=1&p_struct=1&p_annee=2015&p_grtri=6806)

_Il manque quelque chose ? Ecrivez-nous pour que nous le rajoutions à la liste !_